# Generated by Django 4.1.3 on 2022-12-24 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_category_name_alter_category_slug_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        help_text="required, max-30",
                        max_length=30,
                        unique=True,
                        verbose_name="Stock Keeping UNIT",
                    ),
                ),
                (
                    "upc",
                    models.CharField(
                        help_text="required, max-30",
                        max_length=30,
                        unique=True,
                        verbose_name="Universal Product Code",
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "the price must be between 0 to 999.99"
                            }
                        },
                        help_text="Format:maximum Price 999.99",
                        max_digits=5,
                        verbose_name="Retail Price",
                    ),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "the price must be between 0 to 999.99"
                            }
                        },
                        help_text="Format:maximum Price 999.99",
                        max_digits=5,
                        verbose_name="Regular Price",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        help_text="Format: Not Required",
                        null=True,
                        verbose_name="Product Weight",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
