# Generated by Django 4.1.3 on 2022-12-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_productinventorymedia_alter_productinventory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinventorymedia",
            name="product_inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_product_inventory",
                to="inventory.productinventory",
            ),
        ),
    ]
