# Generated by Django 4.1.3 on 2022-12-25 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_productinventorymedia_product_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True,
                        help_text="Format : Not Required",
                        null=True,
                        verbose_name="Last Inventory Stock Checked",
                    ),
                ),
                (
                    "units",
                    models.IntegerField(
                        default=0,
                        help_text="Format : Default 0",
                        verbose_name="Product Unit/stock",
                    ),
                ),
                (
                    "units_sold",
                    models.IntegerField(
                        default=0,
                        help_text="Format : Default 0",
                        verbose_name="Product Unit/stock sold",
                    ),
                ),
                (
                    "product_inventory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_inventory_stock",
                        to="inventory.productinventory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Inventory Stock",
            },
        ),
    ]
