# Generated by Django 4.1.3 on 2022-12-25 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Format : Should Be unique",
                        max_length=100,
                        unique=True,
                        verbose_name="Attribute Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Format : Not Required",
                        null=True,
                        verbose_name="Attribute Description",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Attribute",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_value",
                    models.CharField(
                        help_text="Format : max 255 character",
                        max_length=255,
                        verbose_name="Attribute Value Name",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="Format : Required",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_attribute",
                        to="inventory.productattribute",
                        verbose_name="Attribute Name",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Attribute Value",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValues",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_values",
                        to="inventory.productattributevalue",
                    ),
                ),
                (
                    "product_inventory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_values",
                        to="inventory.productinventory",
                    ),
                ),
            ],
            options={
                "unique_together": {("product_inventory", "attributes")},
            },
        ),
        migrations.AddField(
            model_name="productinventory",
            name="attributes",
            field=models.ManyToManyField(
                related_name="product_attribute_values",
                through="inventory.ProductAttributeValues",
                to="inventory.productattributevalue",
            ),
        ),
    ]
